/* eslint-disable */
// Generated by `pnpm generate:types` — do not edit manually.
// Run `pnpm generate:types` after Payload collections change.

export interface Menu {
  id: string
  slug: 'menu-items'
  number?: number
  name: string
  description?: string
  price?: string
  allergens?: Allergen[]
  tags?: ('ecologico' | 'sin-gluten' | 'vegano' | 'picante')[]
  note?: string
  category: MenuCategory
  createdAt: string
  updatedAt: string
}

export interface MenuCategory {
  id: string
  slug: 'menu-categories'
  name: string
  time?: string
  note?: string
  order?: number
  items?: Menu[]
  createdAt: string
  updatedAt: string
}

export interface Allergen {
  id: string
  slug: 'allergens'
  code: number
  name: string
  createdAt: string
  updatedAt: string
}

export interface Space {
  id: string
  slug: 'spaces'
  heading: string
  intro?: any
  description?: any
  spaces?: string[]
  gallery?: SpaceGallery[]
  cta?: { text?: string; email?: string }
  createdAt: string
  updatedAt: string
}

export interface SpaceGallery {
  image: Media
  alt?: string
  large?: boolean
}

export interface Event {
  id: string
  slug: 'events'
  title: string
  slug: string
  published?: boolean
  date: string
  time?: string
  description?: any
  images?: EventImage[]
  cta?: { label?: string; url?: string }
  createdAt: string
  updatedAt: string
}

export interface EventImage {
  image: Media
  alt?: string
}

export interface Media {
  id: string
  slug: 'media'
  alt?: string
  credit?: string
  url: string
  filename: string
  mimeType: string
  sizes?: {
    thumbnail?: { url: string; width: number; height: number }
    card?: { url: string; width: number; height: number }
    hero?: { url: string; width: number; height: number }
    og?: { url: string; width: number; height: number }
  }
  createdAt: string
  updatedAt: string
}

export interface SiteConfig {
  id: string
  slug: 'site-config'
  name?: string
  tagline?: string
  description?: string
  ogImage?: Media
  contact?: {
    phone?: string
    whatsapp?: string
    email?: string
    reservationsEmail?: string
    eventsEmail?: string
  }
  location?: {
    address?: string
    city?: string
    postalCode?: string
    area?: string
    mapsUrl?: string
    mapsEmbed?: string
    transport?: {
      bus?: { line: string }[]
      parking?: string
      bikeParking?: string
    }
  }
  hours?: {
    weekday?: string
    weekend?: string
    nights?: string
  }
  social?: {
    instagram?: string
    facebook?: string
  }
  externalLinks?: {
    club?: string
    careers?: string
    reservations?: { provider?: string; es?: string; en?: string }
  }
  seo?: Record<
    string,
    {
      homeTitle?: string
      homeDescription?: string
      menuTitle?: string
      spaceTitle?: string
      locationTitle?: string
      bookTitle?: string
    }
  >
  createdAt: string
  updatedAt: string
}
